site_name: Alter Ego Roleplay Bot
nav:
  - Home: index.md
  - Setup Guide: setup-guide.md
theme:
  name: material
  palette:
    scheme: slate
  logo: img/Alter Ego Logo.png
site_url: https://williamgoddard.github.io/alterEgoDocumentation/